#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json

ROOT = Path(__file__).resolve().parents[1]

FIR = ROOT / "runtime" / "fir" / "fir_units.json"
OUTDIR = ROOT / "generated" / "docs"

if not FIR.exists():
    raise SystemExit("ERROR: fir_units.json missing")

fir = json.loads(FIR.read_text())

generated = 0

for unit in fir["units"]:

    ident = unit["identity"]["id"]
    name = unit["identity"]["name"]

    filename = OUTDIR / f"{ident.lower().replace('-','_')}.md"

    text = f"""# {name}

## Module Information

| Field | Value |
|-------|-------|
| Module ID | {ident} |
| Name | {name} |
| Architecture | {unit['architecture']['style']} |
| Status | {unit['classification']['status']} |

## Generated Artifacts

"""

    for artifact, enabled in unit["artifacts"].items():
        mark = "✔" if enabled else "✘"
        text += f"- {mark} {artifact}\n"

    text += f"""

## Quality

Architecture Score: {unit['quality']['architecture_score']}

Checks Passed: {unit['quality']['checks_passed']} / {unit['quality']['checks_total']}

---

Generated by Forge

Generated at: {datetime.now(UTC).isoformat()}
"""

    filename.write_text(text)

    generated += 1

print()
print("Documentation Backend")
print("---------------------")

for file in sorted(OUTDIR.glob("*.md")):
    print(file.name)

print()
print("Generated :", generated)
print("Output    :", OUTDIR)

print()
print("STATUS : BLD0009_DOCUMENTATION_BACKEND_READY")
