#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json

ROOT = Path(__file__).resolve().parents[1]

FIR = ROOT / "runtime/fir/fir_units.json"
OUTDIR = ROOT / "generated/python"

if not FIR.exists():
    raise SystemExit("ERROR: fir_units.json missing")

fir = json.loads(FIR.read_text())

generated = 0

for unit in fir["units"]:

    ident = unit["identity"]["id"]
    name = unit["identity"]["name"]

    filename = OUTDIR / f"{ident.lower().replace('-','_')}.py"

    code = f'''"""
AUTO-GENERATED BY FORGE

Module : {ident}
Name   : {name}
Generated : {datetime.now(UTC).isoformat()}
"""

class {ident.replace("-","_")}:

    MODULE_ID = "{ident}"

    MODULE_NAME = "{name}"

    def run(self):

        print("Running {{self.MODULE_NAME}}")
'''

    filename.write_text(code)

    generated += 1

print()
print("Python Backend")
print("----------------")

for file in sorted(OUTDIR.glob("*.py")):
    print(file.name)

print()
print("Generated :", generated)
print("Output    :", OUTDIR)

print()
print("STATUS : BLD0007_PYTHON_BACKEND_READY")
