#!/usr/bin/env python3

from pathlib import Path
from datetime import datetime, UTC
import json

ROOT = Path(__file__).resolve().parents[1]

FIR = ROOT / "runtime" / "fir" / "fir_units.json"
OUTDIR = ROOT / "generated" / "tests"

if not FIR.exists():
    raise SystemExit("ERROR: fir_units.json missing")

fir = json.loads(FIR.read_text())

generated = 0

for unit in fir["units"]:

    ident = unit["identity"]["id"]
    name = unit["identity"]["name"]

    filename = OUTDIR / f"test_{ident.lower().replace('-','_')}.py"

    code = f'''"""
AUTO-GENERATED BY FORGE

Test Module : {ident}
Target      : {name}
Generated   : {datetime.now(UTC).isoformat()}
"""

import unittest


class Test{ident.replace("-","_")}(unittest.TestCase):

    def test_module_identity(self):
        self.assertEqual("{ident}", "{ident}")

    def test_module_name(self):
        self.assertEqual("{name}", "{name}")

    def test_placeholder(self):
        self.assertTrue(True)


if __name__ == "__main__":
    unittest.main()
'''

    filename.write_text(code)

    generated += 1

print()
print("Test Backend")
print("------------")

for file in sorted(OUTDIR.glob("test_*.py")):
    print(file.name)

print()
print("Generated :", generated)
print("Output    :", OUTDIR)

print()
print("STATUS : BLD0008_TEST_BACKEND_READY")
